### ISSUE TITLE
Pubish v2.1.0

### ISSUE THREAD

**Issue by Dresdn** [ionic-team/prettier-config#6]
The [latest version on npmjs](https://www.npmjs.com/package/@ionic/prettier-config) is v.2.0.0 still. Could you publish v2.1.0?

**Comment by juliengloria** [comment]
@ltm 
"@ionic/prettier-config": "^2.0.0" is still the last version published :)

**Comment by rwaskiewicz** [comment]
Closing, as v2.1.2 of this package was recently published - https://www.npmjs.com/package/@ionic/prettier-config/v/2.1.2
